In [91]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import re
import unicodedata

### Analysing Enrollment data

In [2]:
df1 = pd.read_csv(r"/mnt/c/Rig/Pandoras BOX/Aadhar/api_data_aadhar_enrolment/api_data_aadhar_enrolment_0_500000.csv")
df2 = pd.read_csv(r"/mnt/c/Rig/Pandoras BOX/Aadhar/api_data_aadhar_enrolment/api_data_aadhar_enrolment_500000_1000000.csv")
df3 = pd.read_csv(r"/mnt/c/Rig/Pandoras BOX/Aadhar/api_data_aadhar_enrolment/api_data_aadhar_enrolment_1000000_1006029.csv")

##### Going for df1

In [3]:
df1.sample(5)

,date,state,district,pincode,age_0_5,age_5_17,age_18_greater
176752,13-09-2025,Uttar Pradesh,Agra,283104,2,5,0
430611,18-10-2025,West Bengal,South Twenty Four Parganas,700137,0,1,0
450665,19-10-2025,Rajasthan,Dausa,303304,1,0,0
345028,26-09-2025,Tamil Nadu,Thoothukkudi,628802,1,0,0
364342,13-10-2025,Tamil Nadu,Viluppuram,604151,1,0,0

In [6]:
df1.describe()

             pincode        age_0_5       age_5_17  age_18_greater
count  500000.000000  500000.000000  500000.000000   500000.000000
mean   519204.051054       4.040812       2.315682        0.245558
std    206793.322085      24.417921      20.191196        4.438557
min    100000.000000       0.000000       0.000000        0.000000
25%    362229.000000       1.000000       0.000000        0.000000
50%    517131.000000       2.000000       0.000000        0.000000
75%    712139.000000       3.000000       1.000000        0.000000
max    855456.000000    2688.000000    1812.000000      855.000000

In [96]:
df1.isnull().sum()

date              0
state             0
district          0
pincode           0
age_0_5           0
age_5_17          0
age_18_greater    0
dtype: int64

In [50]:
df1.duplicated().sum()

np.int64(6036)

In [97]:
df1["state"].value_counts()

state
Uttar Pradesh                                   57240
Tamil Nadu                                      45087
West Bengal                                     39965
Maharashtra                                     38194
Karnataka                                       33626
Andhra Pradesh                                  31469
Bihar                                           30626
Rajasthan                                       28408
Madhya Pradesh                                  24323
Odisha                                          22876
Gujarat                                         22718
Telangana                                       22238
Kerala                                          17632
Assam                                           15817
Jharkhand                                       11496
Punjab                                          10499
Chhattisgarh                                     8712
Haryana                                          7529
Jammu and Kashmir                                5311
Uttarakhand                                      4849
Himachal Pradesh                                 4559
Delhi                                            3408
Meghalaya                                        2175
Orissa                                           1786
Tripura                                          1728
Manipur                                          1592
Nagaland                                         1175
Arunachal Pradesh                                 845
Mizoram                                           779
Goa                                               764
Sikkim                                            592
Puducherry                                        496
Pondicherry                                       402
Chandigarh                                        389
Andaman and Nicobar Islands                       133
Ladakh                                            126
Dadra and Nagar Haveli                             89
Lakshadweep                                        73
Jammu & Kashmir                                    63
Dadra and Nagar Haveli and Daman and Diu           61
Andaman & Nicobar Islands                          53
Daman and Diu                                      35
Dadra & Nagar Haveli                               13
West  Bengal                                       12
Daman & Diu                                        10
100000                                              9
West Bangal                                         5
Westbengal                                          3
Jammu And Kashmir                                   2
The Dadra And Nagar Haveli And Daman And Diu        2
andhra pradesh                                      2
West bengal                                         2
WEST BENGAL                                         1
ODISHA                                              1
Name: count, dtype: int64

In [98]:
df2["state"].value_counts()

state
Uttar Pradesh                               52416
Tamil Nadu                                  46795
Maharashtra                                 38454
Karnataka                                   36135
West Bengal                                 36020
Andhra Pradesh                              33949
Bihar                                       29766
Rajasthan                                   27339
Madhya Pradesh                              25533
Gujarat                                     23717
Kerala                                      21133
Odisha                                      20512
Telangana                                   20248
Assam                                       15893
Jharkhand                                   11628
Punjab                                       9848
Chhattisgarh                                 9762
Haryana                                      8412
Jammu and Kashmir                            5966
Himachal Pradesh                             5742
Uttarakhand                                  5088
Delhi                                        3382
Tripura                                      1968
Manipur                                      1600
Meghalaya                                    1571
Orissa                                       1505
Nagaland                                      813
Goa                                           755
Arunachal Pradesh                             748
Mizoram                                       695
Puducherry                                    535
Chandigarh                                    468
Sikkim                                        413
Pondicherry                                   412
Ladakh                                        174
Andaman and Nicobar Islands                   156
Lakshadweep                                    83
Jammu & Kashmir                                76
Dadra and Nagar Haveli                         73
Daman and Diu                                  56
Dadra and Nagar Haveli and Daman and Diu       55
Andaman & Nicobar Islands                      50
100000                                         13
Dadra & Nagar Haveli                           11
Daman & Diu                                    10
West bengal                                     5
West Bangal                                     4
andhra pradesh                                  3
West  Bengal                                    3
Westbengal                                      3
WEST BENGAL                                     3
WESTBENGAL                                      1
Name: count, dtype: int64

In [ ]:
df3["state"].value_counts()

In [11]:
# rectification needed in state names:
# West Bengal, Daman and Diu, Odisha, Andaman and Nicobar islands, Andhra Pradesh.... and many misspellings
# there are unknown state names also (in the name of 10000)

In [65]:
df1['state'].nunique()
#df2['state'].nunique()
#df3['state'].nunique()

54

In [66]:
df_combined = pd.concat([df1, df2, df3], axis=0, ignore_index=True, verify_integrity=True)

In [67]:
df_combined

,date,state,district,pincode,age_0_5,age_5_17,age_18_greater
0,02-03-2025,Meghalaya,East Khasi Hills,793121,11,61,37
1,09-03-2025,Karnataka,Bengaluru Urban,560043,14,33,39
2,09-03-2025,Uttar Pradesh,Kanpur Nagar,208001,29,82,12
3,09-03-2025,Uttar Pradesh,Aligarh,202133,62,29,15
4,09-03-2025,Karnataka,Bengaluru Urban,560016,14,16,21
...,...,...,...,...,...,...,...
1006024,31-12-2025,West Bengal,West Midnapore,721149,2,0,0
1006025,31-12-2025,West Bengal,West Midnapore,721150,2,2,0
1006026,31-12-2025,West Bengal,West Midnapore,721305,0,1,0
1006027,31-12-2025,West Bengal,West Midnapore,721504,1,0,0
1006028,31-12-2025,West Bengal,West Midnapore,721517,2,1,0

In [68]:
df_combined["state"].nunique()

55

In [75]:
def process(df):    
    df["state"] = df["state"].str.upper()
    df["district"] = df["district"].str.upper()
    df['state'] = df['state'].replace(r'\s+', ' ', regex=True)
    df = df.drop_duplicates(keep='first', ignore_index=True)
    return df

In [76]:
df_process = process(df_combined)
df_process

,date,state,district,pincode,age_0_5,age_5_17,age_18_greater
0,02-03-2025,MEGHALAYA,EAST KHASI HILLS,793121,11,61,37
1,09-03-2025,KARNATAKA,BENGALURU URBAN,560043,14,33,39
2,09-03-2025,UTTAR PRADESH,KANPUR NAGAR,208001,29,82,12
3,09-03-2025,UTTAR PRADESH,ALIGARH,202133,62,29,15
4,09-03-2025,KARNATAKA,BENGALURU URBAN,560016,14,16,21
...,...,...,...,...,...,...,...
982994,31-12-2025,WEST BENGAL,WEST MIDNAPORE,721149,2,0,0
982995,31-12-2025,WEST BENGAL,WEST MIDNAPORE,721150,2,2,0
982996,31-12-2025,WEST BENGAL,WEST MIDNAPORE,721305,0,1,0
982997,31-12-2025,WEST BENGAL,WEST MIDNAPORE,721504,1,0,0
982998,31-12-2025,WEST BENGAL,WEST MIDNAPORE,721517,2,1,0

In [77]:
df_process["state"].value_counts()

state
UTTAR PRADESH                                   108066
TAMIL NADU                                       90388
MAHARASHTRA                                      75531
WEST BENGAL                                      75350
KARNATAKA                                        68756
ANDHRA PRADESH                                   63836
BIHAR                                            58542
RAJASTHAN                                        54864
MADHYA PRADESH                                   49562
GUJARAT                                          45243
ODISHA                                           42695
TELANGANA                                        41878
KERALA                                           38581
ASSAM                                            30699
JHARKHAND                                        22651
PUNJAB                                           20081
CHHATTISGARH                                     17981
HARYANA                                          15522
JAMMU AND KASHMIR                                11063
HIMACHAL PRADESH                                 10059
UTTARAKHAND                                       9809
DELHI                                             6640
MEGHALAYA                                         3678
TRIPURA                                           3634
ORISSA                                            3240
MANIPUR                                           3145
NAGALAND                                          1951
ARUNACHAL PRADESH                                 1553
GOA                                               1490
MIZORAM                                           1443
PUDUCHERRY                                        1025
SIKKIM                                             993
CHANDIGARH                                         826
PONDICHERRY                                        807
LADAKH                                             304
ANDAMAN AND NICOBAR ISLANDS                        283
DADRA AND NAGAR HAVELI                             160
LAKSHADWEEP                                        156
JAMMU & KASHMIR                                    131
DADRA AND NAGAR HAVELI AND DAMAN AND DIU           113
ANDAMAN & NICOBAR ISLANDS                          100
DAMAN AND DIU                                       87
DADRA & NAGAR HAVELI                                24
100000                                              21
DAMAN & DIU                                         20
WEST BANGAL                                          9
WESTBENGAL                                           7
THE DADRA AND NAGAR HAVELI AND DAMAN AND DIU         2
Name: count, dtype: int64

In [82]:
df_process["state"].nunique()

48

In [79]:
df_process["district"].nunique()

965

In [80]:
df_process["district"].unique()

array(['EAST KHASI HILLS', 'BENGALURU URBAN', 'KANPUR NAGAR', 'ALIGARH',
       'SITAMARHI', 'BAHRAICH', 'FIROZABAD', 'PURBI CHAMPARAN',
       'MAHARAJGANJ', 'AURANGABAD', 'GHAZIABAD', 'FARIDABAD', 'MADHUBANI',
       'SIKAR', 'BHAGALPUR', 'AMRITSAR', 'GURUGRAM',
       'GAUTAM BUDDHA NAGAR', 'WEST DELHI', 'BHIND', 'GWALIOR', 'KATNI',
       'COOCHBEHAR', 'LUCKNOW', 'DINAJPUR UTTAR', 'MARIGAON', 'KOKRAJHAR',
       'AGRA', 'HARIDWAR', 'NAGAON', 'PARBHANI', 'WEST KHASI HILLS',
       'NORTH WEST DELHI', 'WEST JAINTIA HILLS', 'UNNAO', 'SAHARANPUR',
       'DIBRUGARH', 'UDALGURI', 'CHIRANG', 'KAMRUP', 'DHUBRI', 'JAUNPUR',
       'THANE', 'DHEMAJI', 'BANAS KANTHA', 'TINSUKIA', 'SPSR NELLORE',
       'BARPETA', 'SONITPUR', 'BAKSA', 'LUDHIANA', 'PATAN', 'KANCHIPURAM',
       'PATNA', 'LAKHIMPUR', 'BONGAIGAON', 'VADODARA', 'NAINITAL',
       'DEHRADUN', 'HOJAI', 'DOHAD', 'MORBI', 'RAIPUR', 'GORAKHPUR',
       'BULANDSHAHR', 'MATHURA', 'PASHCHIM CHAMPARAN', 'BIJAPUR',
       'DEOGHAR', 'MUZAFFARPUR', 'BANDA', 'KACHCHH', 'RI BHOI', 'DARRANG',
       'ASHOK NAGAR', 'DARJEELING', 'NORTH CACHAR HILLS', 'RANCHI',
       'SURAT', 'NANDED', 'BENGALURU', 'JORHAT', 'GIR SOMNATH',
       'KAMRUP METRO', 'GOALPARA', 'BHAVNAGAR', 'GOLAGHAT', 'NAGPUR',
       'COOCH BEHAR', 'JALGAON', 'HINGOLI', 'AHMADNAGAR', 'GANDHINAGAR',
       'NORTH 24 PARGANAS', 'MUNGER', 'KOHIMA', 'JALOR', 'KHEDA',
       'NALBARI', 'PALGHAR', 'JODHPUR', 'CENTRAL DELHI', 'GAYA',
       'SABARKANTHA', 'DIMAPUR', 'CACHAR', 'BANASKANTHA', 'KHERI',
       'RAJKOT', 'SATARA', 'BETUL', 'WEST KARBI ANGLONG', 'SOUTH DELHI',
       'RAIGAD', 'UTTAR DINAJPUR', 'GUNA', 'KAIMUR (BHABUA)', 'DHOLPUR',
       'CHURACHANDPUR', 'WEST CHAMPARAN', 'BHARUCH', 'JHARGRAM',
       'KHARGONE', 'CHHOTAUDEPUR', 'MUMBAI SUBURBAN', 'HAILAKANDI',
       'PANCHMAHALS', 'SOUTH SALMARA MANKACHAR', 'BUDAUN', 'KANPUR DEHAT',
       'PORBANDAR', 'WEST GARO HILLS', 'KAPURTHALA', 'SOUTH GARO HILLS',
       'NAGAUR', 'MYSURU', 'MAHESANA', 'CHURU', 'HYDERABAD',
       'KANCHEEPURAM', 'VARANASI', 'LOHARDAGA', 'NORTH GARO HILLS',
       'CHHATARPUR', 'NADIA', 'PURNIA', 'GURGAON', 'CHARAIDEO', 'JAIPUR',
       'SARAN', 'MORENA', 'DHAR', 'DAHOD', 'DEVBHUMI DWARKA',
       'EAST CHAMPARAN', 'TAPI', 'BAGHPAT', 'FATEHPUR',
       'SOUTH WEST KHASI HILLS', 'YADGIR', 'NANDURBAR', 'ETAWAH',
       'JALPAIGURI', 'JABALPUR', 'SHAMLI', 'SIBSAGAR', 'BARWANI', 'BOTAD',
       'JUNAGADH', 'BALRAMPUR', 'BARA BANKI', 'SHIVPURI', 'BEED',
       'SHAHJAHANPUR', 'JAMNAGAR', 'CHANDRAPUR', 'DURG',
       'K.V. RANGAREDDY', 'SIROHI', 'ALIPURDUAR', 'SOUTH WEST DELHI',
       'GONDA', 'EAST JAINTIA HILLS', 'BAREILLY', 'BUNDI', 'SOLAPUR',
       'SITAPUR', 'DUMKA', 'SULTANPUR', 'KARBI ANGLONG', 'BIKANER',
       'PHEK', 'RAISEN', 'SHRAWASTI', 'EAST DELHI', 'JHABUA', 'UNAKOTI',
       'INDORE', 'BHOPAL', 'DUNGARPUR', 'CHANDAULI', 'BHARATPUR',
       'MAINPURI', 'GODDA', 'MUZAFFARNAGAR', 'SIDDHARTHNAGAR', 'DATIA',
       'WEST TRIPURA', 'MEDCHAL-MALKAJGIRI', 'SAGAR', 'SHEOPUR',
       'ARVALLI', 'SURENDRA NAGAR', 'MALDA', 'AMRELI', 'ALWAR',
       'AMBEDKAR NAGAR', 'MADURAI', 'PILIBHIT', 'CHAMPHAI', 'VALSAD',
       'PAKUR', 'VAISHALI', 'VIDISHA', 'KARIMGANJ', 'BISWANATH',
       'BURHANPUR', 'KAUSHAMBI', 'PUNE', 'PUNCH', 'JEHANABAD', 'JALAUN',
       'ETAH', 'MEERUT', 'BARAN', 'SANGRUR', 'KARAULI', 'ANAND',
       'LONGLENG', 'CHANDIGARH', 'JAMUI', 'SOUTH SIKKIM', 'PANNA',
       'EAST GARO HILLS', 'JHALAWAR', 'SHAHDARA', 'KALABURAGI',
       'THANJAVUR', 'PEREN', 'TUENSANG', 'MAHISAGAR', 'HOSHIARPUR',
       'NOKLAK', 'SUKMA', 'KHANDWA', 'AJMER', 'WEST SIKKIM', 'LATUR',
       'BASTI', 'SATNA', 'GURDASPUR', 'HAZARIBAGH', 'AZAMGARH', 'UDAIPUR',
       'KOLKATA', 'RAMPUR', 'THE DANGS', 'EAST SINGHBHUM', 'ALIRAJPUR',
       'SAS NAGAR (MOHALI)', 'SOUTH WEST GARO HILLS', 'MORADABAD', 'KOTA',
       'DEWAS', 'NAVSARI', 'CHUMUKEDIMA', 'AHMEDABAD', 'NABARANGAPUR',
       'PALI', 'AMROHA', 'SAIHA', 'DAKSHIN DINAJPUR', 'BIJNOR',
       'PUDUKKOTTAI', 'BANGALORE RURAL', 'KALIMPONG', 'DEORIA',
       'BARAMULA', 'GOPALGANJ', 'PRAYAGRAJ', 'LALITPUR', 'MEWAT', 'HAPUR',
       'JAMMU', 'BISHNUPUR', 'SAHARSA', 'ARWAL', 'HATHRAS', 'LAWNGTLAI',
       'NASHIK', 'YAVATMAL', 'CUDDALORE', 'KOLLAM', 'PATIALA', 'KATIHAR',
       'MALAPPURAM', 'BIRBHUM', 'SIWAN', 'DHULE', 'BALODA BAZAR',
       'WASHIM', 'COIMBATORE', 'LUNGLEI', 'IMPHAL WEST', 'KUSHINAGAR',
       'THIRUVANANTHAPURAM', 'SANGLI', 'AHMADABAD', 'LAKHISARAI',
       'BENGALURU RURAL', '24 PARAGANAS NORTH', 'DIMA HASAO', 'BANKA',
       'SALEM', 'DADRA AND NAGAR HAVELI', 'DANG', 'KAITHAL', 'VELLORE',
       'SHRAVASTI', 'NALANDA', 'JAISALMER', 'KALLAKURICHI', 'FARRUKHABAD',
       'MEDINIPUR WEST', 'ARARIA', 'SONIPAT', 'CHATRA',
       'GAURELLA PENDRA MARWAHI', 'VISAKHAPATANAM', 'BULDHANA',
       'AMRAVATI', 'HARDOI', 'DHALAI', 'ERNAKULAM', 'NEW DELHI',
       'BHILWARA', 'RAMANATHAPURAM', 'MON', 'RAICHUR', 'NORTH DELHI',
       'ROHTAK', 'GUMLA', 'BARMER', 'KURUKSHETRA', 'NUH', 'ASHOKNAGAR',
       'THRISSUR', 'S.A.S NAGAR', 'NORTH EAST DELHI', 'PURBA BARDHAMAN',
       'AMBALA', 'PANIPAT', 'DARBHANGA', 'AYODHYA', 'KHUNTI',
       'MEDCHAL MALKAJGIRI', 'SIVASAGAR', 'HISAR', 'SIVAGANGA',
       'SIDDHARTH NAGAR', 'WEST KAMENG', 'KULLU', 'KHORDHA', 'BARABANKI',
       'CHENGALPATTU', 'AHMEDNAGAR', 'JALORE', 'NAWADA', 'HOOGHLY',
       '24 PARAGANAS SOUTH', 'CHENNAI', 'SURENDRANAGAR', 'MUMBAI',
       'NABARANGPUR', 'SABAR KANTHA', 'RAMANAGARA', 'WOKHA',
       'WEST SINGHBHUM', 'SEPAHIJALA', 'SAMASTIPUR', 'ZUNHEBOTO',
       'EAST SINGHBUM', 'SAMBHAL', 'CHITTORGARH', 'PANCH MAHALS', 'BIDAR',
       'TONK', 'LONGDING', 'JHANSI', 'HOWRAH', 'RAIGARH', 'GIRIDIH',
       'AKOLA', 'NORTH GOA', 'VIJAYAPURA', 'BEGUSARAI', 'RANGA REDDY',
       'THIRUVALLUR', 'BHADRADRI KOTHAGUDEM', 'HANUMANGARH', 'KANNUR',
       'TARN TARAN', 'MAJULI', 'BALAGHAT', 'KIPHIRE', 'DINAJPUR DAKSHIN',
       'EAST NIMAR', 'OSMANABAD', 'DHANBAD', 'KASGANJ', 'SHOPIAN',
       'SEHORE', 'KANNAUJ', 'NARSINGHPUR', 'BILASPUR', 'KOLASIB',
       'SAWAI MADHOPUR', 'NORTH TRIPURA', 'KUSHI NAGAR', 'PRAKASAM',
       'BHOJPUR', 'HOSHANGABAD', 'DODA', 'MOKOKCHUNG', 'GOMATI',
       'KRISHNA', 'KURNOOL', 'MAHABUB NAGAR', 'MAHBUBNAGAR', 'MEDAK',
       'N. T. R', 'NALGONDA', 'NANDYAL', 'NELLORE', 'PALNADU',
       'RANGAREDDI', 'SRI POTTI SRIRAMULU NELLORE', 'SRI SATHYA SAI',
       'SRIKAKULAM', 'TIRUPATI', 'VISAKHAPATNAM', 'VIZIANAGARAM',
       'WARANGAL', 'WEST GODAVARI', 'Y. S. R', 'CHANGLANG', 'EAST KAMENG',
       'TAWANG', 'WEST SIANG', 'BAJALI', 'SRIBHUMI', 'BUXAR', 'KHAGARIA',
       'KISHANGANJ', 'MADHEPURA', 'ROHTAS', 'SHEOHAR', 'SUPAUL', 'BASTAR',
       'BEMETARA', 'GARIYABAND', 'JASHPUR', 'KAWARDHA', 'KONDAGAON',
       'KORBA', 'MANENDRAGARH–CHIRMIRI–BHARATPUR', 'RAJNANDGAON', 'SAKTI',
       'SARANGARH-BILAIGARH', 'SURAJPUR', 'SURGUJA', 'SOUTH GOA',
       'NARMADA', 'BHIWANI', 'CHARKHI DADRI', 'FATEHABAD', 'JHAJJAR',
       'JIND', 'KARNAL', 'MAHENDRAGARH', 'REWARI', 'SIRSA',
       'YAMUNA NAGAR', 'HAMIRPUR', 'KANGRA', 'MANDI', 'SIRMAUR', 'SOLAN',
       'UNA', 'ANANTNAG', 'BADGAM', 'BANDIPORE', 'BUDGAM', 'KARGIL',
       'KATHUA', 'KUPWARA', 'LEH', 'PULWAMA', 'RAJOURI', 'RAMBAN',
       'REASI', 'SAMBA', 'SRINAGAR', 'UDHAMPUR', 'BOKARO', 'GARHWA',
       'GARHWA *', 'HAZARIBAG', 'JAMTARA', 'LATEHAR', 'PALAMAU', 'PALAMU',
       'PURBI SINGHBHUM', 'RAMGARH', 'SAHEBGANJ', 'SERAIKELA-KHARSAWAN',
       'SIMDEGA', 'BAGALKOT', 'BAGALKOT *', 'BALLARI', 'BANGALORE',
       'BELAGAVI', 'BELGAUM', 'BELLARY', 'CHAMARAJANAGAR',
       'CHAMRAJANAGAR', 'CHAMRAJNAGAR', 'CHICKMAGALUR', 'CHIKKABALLAPUR',
       'CHIKKAMAGALURU', 'CHIKMAGALUR', 'CHITRADURGA', 'DAKSHINA KANNADA',
       'DAVANAGERE', 'DAVANGERE', 'DHARWAD', 'GADAG', 'GADAG *',
       'GULBARGA', 'HASSAN', 'HAVERI', 'KODAGU', 'KOLAR', 'KOPPAL',
       'MANDYA', 'MYSORE', 'RAMANAGAR', 'SHIMOGA', 'SHIVAMOGGA',
       'TUMAKURU', 'TUMKUR', 'UDUPI', 'UTTARA KANNADA', 'VIJAYANAGARA',
       'ALAPPUZHA', 'IDUKKI', 'KASARAGOD', 'KASARGOD', 'KOTTAYAM',
       'KOZHIKODE', 'PALAKKAD', 'PATHANAMTHITTA', 'WAYANAD', 'AGAR MALWA',
       'ANUPPUR', 'CHHINDWARA', 'DAMOH', 'DINDORI', 'HARDA', 'MAIHAR',
       'MANDLA', 'MANDSAUR', 'NARMADAPURAM', 'NARSIMHAPUR', 'NEEMUCH',
       'NIWARI', 'RAJGARH', 'RATLAM', 'REWA', 'SEONI', 'SHAHDOL',
       'SHAJAPUR', 'SIDHI', 'SINGRAULI', 'TIKAMGARH', 'UJJAIN',
       'WEST NIMAR', 'AHMED NAGAR', 'BHANDARA', 'BULDANA',
       'CHHATRAPATI SAMBHAJINAGAR', 'GADCHIROLI', 'GONDIYA', 'JALNA',
       'KOLHAPUR', 'MUMBAI CITY', 'RATNAGIRI', 'SINDHUDURG', 'WARDHA',
       'SENAPATI', 'TAMENGLONG', 'AIZAWL', 'ANGUL', 'NICOBAR',
       'SOUTH ANDAMAN', 'ADILABAD', 'ALLURI SITHARAMA RAJU', 'ANAKAPALLI',
       'ANANTAPUR', 'ANANTHAPUR', 'ANANTHAPURAMU', 'BAPATLA', 'CHITTOOR',
       'CUDDAPAH', 'DR. B. R. AMBEDKAR KONASEEMA', 'EAST GODAVARI',
       'ELURU', 'GUNTUR', 'KAKINADA', 'KARIMNAGAR', 'KHAMMAM', 'ANUGUL',
       'BALANGIR', 'BALESWAR', 'BARGARH', 'BAUDH', 'BHADRAK', 'BOUDH',
       'CUTTACK', 'DEBAGARH', 'DHENKANAL', 'GAJAPATI', 'GANJAM', 'JAJPUR',
       'JAGATSINGHAPUR', 'JAGATSINGHPUR', 'JAJAPUR', 'KALAHANDI',
       'KANDHAMAL', 'KENDRAPARA', 'KENDUJHAR', 'KHORDA', 'KORAPUT',
       'MALKANGIRI', 'MAYURBHANJ', 'NAYAGARH', 'NUAPADA', 'PURI',
       'RAYAGADA', 'SAMBALPUR', 'SONAPUR', 'SUBARNAPUR', 'SUNDARGARH',
       'SUNDERGARH', 'BALESHWAR', 'PONDICHERRY', 'KARAIKAL', 'PUDUCHERRY',
       'YANAM', 'BARNALA', 'BATHINDA', 'FARIDKOT', 'FATEHGARH SAHIB',
       'FEROZEPUR', 'FIROZPUR', 'JALANDHAR', 'MALERKOTLA', 'MANSA',
       'MUKTSAR', 'PATHANKOT', 'RUPNAGAR', 'SHAHEED BHAGAT SINGH NAGAR',
       'SRI MUKTSAR SAHIB', 'BANSWARA', 'CHITTAURGARH', 'DAUSA',
       'GANGANAGAR', 'JHUNJHUNUN', 'PRATAPGARH', 'RAJSAMAND', 'EAST',
       'NORTH SIKKIM', 'SOUTH', 'ARIYALUR', 'DHARMAPURI', 'DINDIGUL',
       'ERODE', 'KANNIYAKUMARI', 'KANYAKUMARI', 'KARUR', 'KRISHNAGIRI',
       'MAYILADUTHURAI', 'NAGAPATTINAM', 'NAMAKKAL', 'PERAMBALUR',
       'RANIPET', 'TENKASI', 'THE NILGIRIS', 'THENI', 'THIRUVARUR',
       'THOOTHUKKUDI', 'TIRUCHIRAPPALLI', 'TIRUNELVELI', 'TIRUPATTUR',
       'TIRUPPUR', 'TIRUVALLUR', 'TIRUVANNAMALAI', 'VILLUPURAM',
       'VILUPPURAM', 'VIRUDHUNAGAR', 'HANUMAKONDA', 'JAGITIAL', 'JANGOAN',
       'JAYASHANKAR BHUPALPALLY', 'JOGULAMBA GADWAL', 'KAMAREDDY',
       'KOMARAM BHEEM', 'MAHABUBABAD', 'MAHABUBNAGAR', 'MANCHERIAL',
       'MEDCHAL−MALKAJGIRI', 'MULUGU', 'NAGARKURNOOL', 'NARAYANPET',
       'NIRMAL', 'NIZAMABAD', 'PEDDAPALLI', 'RAJANNA SIRCILLA',
       'SANGAREDDY', 'SIDDIPET', 'SURYAPET', 'VIKARABAD', 'WANAPARTHY',
       'WARANGAL RURAL', 'WARANGAL URBAN', 'YADADRI.', 'KHOWAI',
       'SOUTH TRIPURA', 'ALLAHABAD', 'AMETHI', 'AURAIYA', 'BALLIA',
       'BHADOHI', 'CHITRAKOOT', 'FAIZABAD', 'GHAZIPUR', 'MAHOBA', 'MAU',
       'MIRZAPUR', 'RAE BARELI', 'SANT KABIR NAGAR', 'SANT RAVIDAS NAGAR',
       'SONBHADRA', 'ALMORA', 'BAGESHWAR', 'CHAMOLI', 'GARHWAL',
       'PAURI GARHWAL', 'PITHORAGARH', 'RUDRAPRAYAG', 'TEHRI GARHWAL',
       'UDHAM SINGH NAGAR', 'UTTARKASHI', 'BANKURA', 'BARDDHAMAN',
       'BARDHAMAN', 'DARJILING', 'EAST MIDNAPORE', 'HAORA', 'KOCH BIHAR',
       'MALDAH', 'MURSHIDABAD', 'NORTH TWENTY FOUR PARGANAS',
       'PASCHIM BARDHAMAN', 'PASCHIM MEDINIPUR', 'PURBA MEDINIPUR',
       'PURULIA', 'PURULIYA', 'SOUTH 24 PARGANAS', 'SOUTH DINAJPUR',
       'SOUTH TWENTY FOUR PARGANAS', 'WEST MIDNAPORE', 'NORTH EAST',
       'PARVATHIPURAM MANYAM', 'KURUNG KUMEY', 'LOHIT',
       'LOWER DIBANG VALLEY', 'PAPUM PARE', 'UPPER SIANG',
       'AURANGABAD(BH)', 'PURBA CHAMPARAN', 'PURNEA', 'SHEIKHPURA',
       'BALOD', 'DHAMTARI', 'GAURELA-PENDRA-MARWAHI', 'JANJGIR-CHAMPA',
       'KABEERDHAM', 'KANKER', 'KHAIRAGARH CHHUIKHADAN GANDAI', 'KORIYA',
       'MAHASAMUND', 'MOHLA-MANPUR-AMBAGARH CHOUKI', 'MUNGELI',
       'NARAYANPUR', 'PALWAL', 'CHAMBA', 'SHIMLA', 'GANDERBAL', 'KODARMA',
       'PAKAUR', 'SAHIBGANJ', 'HASAN', 'LAKSHADWEEP', 'HARDA *',
       'MAUGANJ', 'UMARIA', 'CHATRAPATI SAMBHAJI NAGAR',
       'MUMBAI( SUB URBAN )', 'NANDURBAR *', 'IMPHAL EAST', 'THOUBAL',
       'UKHRUL', 'EASTERN WEST KHASI HILLS', 'MAMIT', 'SERCHHIP',
       'ANDAMANS', 'NORTH AND MIDDLE ANDAMAN', 'ANNAMAYYA',
       'K.V.RANGAREDDY', 'KARIM NAGAR', 'RANGAREDDY', 'BULANDSHAHAR',
       'HUGLI', 'NORTH DINAJPUR', 'JHARSUGUDA', 'FAZILKA', 'MOGA',
       'NORTH', 'CHANDEL', 'KAKCHING', 'S.A.S NAGAR(MOHALI)', 'JHUNJHUNU',
       'EAST SIKKIM', 'WEST', 'LOWER SUBANSIRI', 'NAMSAI', 'SHEIKPURA',
       'DAKSHIN BASTAR DANTEWADA', 'DADRA & NAGAR HAVELI', 'DAMAN',
       'PANCHKULA', 'KISHTWAR', 'SHUPIYAN', 'PASHCHIMI SINGHBHUM',
       'PANDHURNA', 'BID', 'GONDIYA *', 'JYOTIBA PHULE NAGAR',
       'SANT RAVIDAS NAGAR BHADOHI', 'MELURI', 'DHAULPUR', 'ANJAW',
       'EAST SIANG', 'TAMULPUR DISTRICT', 'DANTEWADA', 'KODERMA',
       'CHAMARAJANAGAR *', 'DHARASHIV', 'GONDIA', 'DHALAI  *', 'KULGAM',
       'JIRIBAM', 'SAITUAL', 'KRA DAADI', 'UPPER SUBANSIRI', 'BHABUA',
       'CHAMPAWAT', 'KAMLE', 'HAVERI *', 'MAMMIT', 'SHAMATOR',
       'NAWANSHAHR', 'JANGAON', '100000', 'MONGHYR',
       'UTTAR BASTAR KANKER', 'SOUTH EAST DELHI', 'SAMSTIPUR', 'DIU',
       'NAJAFGARH', 'KINNAUR', 'TUTICORIN', 'WARANGAL (URBAN)', 'SIANG',
       'TIRAP', 'NAMCHI', 'HARDWAR', 'NIULAND', 'SHI-YOMI', 'KHAWZAWL',
       'JANJGIR - CHAMPA', 'LAHUL AND SPITI', 'JANJGIR CHAMPA',
       'WASHIM *', 'NICOBARS', 'LOWER SIANG', 'YAMUNANAGAR',
       'LAHUL & SPITI', 'JHAJJAR *', 'RAEBARELI', 'HAWRAH',
       'BENGALURU SOUTH', 'RAIGARH(MH)', 'TIRUPATHUR', 'DIBANG VALLEY',
       'DEEG\xa0', 'LEPARADA', 'MEDCHAL?MALKAJGIRI', 'MEDINIPUR',
       'MOHALLA-MANPUR-AMBAGARH CHOWKI', 'TSEMINYU', 'MAHRAJGANJ',
       'HNAHTHIAL', 'PAKKE KESSANG', 'KUSHINAGAR *', 'TIRUVARUR',
       'EAST MIDNAPUR', 'HINGOLI *', 'NORTH EAST   *', 'BARDEZ',
       'NAMAKKAL   *', 'HOOGHIY', 'PHERZAWL', 'JAINTIA HILLS',
       'WEST MEDINIPUR', 'LAHAUL AND SPITI', 'BURDWAN', 'BANDIPUR',
       'MANGAN', 'LEH (LADAKH)', 'BOKARO *', 'SOUTH 24 PARGANA', 'DEEG',
       'ANUGAL', 'UDUPI *', 'KENDRAPARA *', 'RAJAURI', 'BIJAPUR(KAR)',
       'BAGPAT', 'BALOTRA', 'AHILYANAGAR', 'DIDWANA-KUCHAMAN', 'SALUMBAR',
       'BEAWAR'], dtype=object)

In [104]:
state_mapping = {
    # Misspellings
    "WESTBENGAL" : "WEST BENGAL",
    "WEST BANGAL" : "WEST BENGAL",
    "JAMMU & KASHMIR": "JAMMU AND KASHMIR",
    "ANDAMAN & NICOBAR ISLANDS" : "ANDAMAN AND NICOBAR ISLANDS",

    # Name updates
    "ORISSA": "ODISHA",
    "PONDICHERRY": "PUDUCHERRY",
    
    "THE DADRA AND NAGAR HAVELI AND DAMAN AND DIU" : "DADRA AND NAGAR HAVELI AND DAMAN AND DIU",
    "DAMAN AND DIU" : "DADRA AND NAGAR HAVELI AND DAMAN AND DIU",
    "DAMAN & DIU" : "DADRA AND NAGAR HAVELI AND DAMAN AND DIU",
    "DADRA AND NAGAR HAVELI" : "DADRA AND NAGAR HAVELI AND DAMAN AND DIU",
    "DADRA & NAGAR HAVELI" : "DADRA AND NAGAR HAVELI AND DAMAN AND DIU",

    # The unnamed states
    "100000" : "UNKNOWN"
}

In [105]:
df_process["state"] = df_process["state"].replace(state_mapping)

In [106]:
df_process["state"].nunique()   # Should be equal to 28(states) + 8(UT) +1(unknown)

37

In [85]:
state_cleaned_df = df_process.copy()
state_cleaned_df

,date,state,district,pincode,age_0_5,age_5_17,age_18_greater
0,02-03-2025,MEGHALAYA,EAST KHASI HILLS,793121,11,61,37
1,09-03-2025,KARNATAKA,BENGALURU URBAN,560043,14,33,39
2,09-03-2025,UTTAR PRADESH,KANPUR NAGAR,208001,29,82,12
3,09-03-2025,UTTAR PRADESH,ALIGARH,202133,62,29,15
4,09-03-2025,KARNATAKA,BENGALURU URBAN,560016,14,16,21
...,...,...,...,...,...,...,...
982994,31-12-2025,WEST BENGAL,WEST MIDNAPORE,721149,2,0,0
982995,31-12-2025,WEST BENGAL,WEST MIDNAPORE,721150,2,2,0
982996,31-12-2025,WEST BENGAL,WEST MIDNAPORE,721305,0,1,0
982997,31-12-2025,WEST BENGAL,WEST MIDNAPORE,721504,1,0,0
982998,31-12-2025,WEST BENGAL,WEST MIDNAPORE,721517,2,1,0

In [86]:
##district cleaning pipeline

def normalize_district(s):
    if pd.isna(s):
        return np.nan

    s = str(s)

    s = unicodedata.normalize("NFKD",s) ##decomposes the characters to base level unicode representation
    s = s.encode('ascii','ignore').decode('ascii')
    
    s = s.lower()
    s = s.replace('&','and')
    s = s.replace("−", "-").replace("–", "-").replace("—", "-") ##hyphen normalizatoin

    s = re.sub(r"[\(\)\[\]\{\}]"," ",s) ##removing junk brackets
    s = re.sub(r"[^\w\s\-]"," ",s) ##junk punctuations

    for k, v in NUMBER_WORDS.items():
        s = re.sub(rf"\b{k}\b", v, s)
        
    s = re.sub(r"\b20\s+4\b", "24", s)
    s = re.sub(r"\s+"," ",s).strip() ##collapse spaces

    if re.fullmatch(r'\d+',s):
        return np.nan ## district names can't be numbers

    return s

##allowed directions
DIRECTION_ONLY = {
        "north", "south", "east", "west",
    "north east", "north west", "south east", "south west"
}

##sub localities
GARBAGE_PATTERNS = [
    r"\bnear\b",
    r"\broad\b",
    r"\bcolony\b",
    r"\bcross\b",
    r"\bthana\b",
    r"\bsector\b",
    r"\bward\b",
    r"\bblock\b",
]


EXPLICIT_GARBAGE = {
    "domjur",
    "bardez",
    "tiswadi",
    "najafgarh",
    "bally jagachha",
    "south dumdum m",
}


def is_garbage(s):
    if s is None or pd.isna(s):
        return True

    s = s.strip()

    if len(s) <= 2:
        return True

    if s in DIRECTION_ONLY:
        return True

    if s in EXPLICIT_GARBAGE:
        return True


    for pat in GARBAGE_PATTERNS:
        if re.search(pat,s):
            return True

    return False


NUMBER_WORDS = {
    "one": "1", "two": "2", "three": "3", "four": "4",
    "five": "5", "six": "6", "seven": "7", "eight": "8",
    "nine": "9", "ten": "10", "twenty": "20",
}

#minimal cannonical map
CANONICAL_MAP = {

    # ---- spelling duplicates ----
    "viluppuram": "villupuram",
    "rangareddi": "rangareddy",
    "buldana": "buldhana",
    "hazaribag": "hazaribagh",
    "malda": "maldah",
    "puruliya": "purulia",
    "jhunjhunun": "jhunjhunu",
    "khorda": "khordha",

    # ---- Andhra normalization ----
    "ananthapur": "ananthapuramu",
    "anantapur": "ananthapuramu",

    #------ Karnataka-----
    # 'Chickmagalur':'Chikmagalur',
    "Chikkaballapur":"Chikmagalur",
    "Chikkamagaluru":"Chikmagalur",
    "Chikmagalur":"Chikmagalur",

    # ---- Numeric normalization ----
    "north 24 parganas": "north 24 parganas",
    "north twenty four parganas": "north 24 parganas",
    "south 24 parganas": "south 24 parganas",
    "south twenty four parganas": "south 24 parganas",

    # ---- Renamed districts ----
    "allahabad": "prayagraj",
    "aurangabad bh": "chhatrapati sambhajinagar",
    "osmanabad": "dharashiv",

    # ---- Merged UT ----
    "diu": "dadra and nagar haveli and daman and diu",
    "dadra and nagar haveli": "dadra and nagar haveli and daman and diu",
    "daman and diu": "dadra and nagar haveli and daman and diu",
}

CANONICAL_MAP.update({

    # ---- West Bengal ----
    "hugli": "hooghly",
    "hooghiy": "hooghly",
    "haora": "howrah",
    "medinipur": "paschim medinipur",

    # ---- Odisha ----
    "baleswar": "baleshwar",
    "sonapur": "subarnapur",

    # ---- Maharashtra ----
    "ahmadnagar": "ahilyanagar",
    "ahmednagar": "ahilyanagar",
    "chatrapati sambhaji nagar": "chhatrapati sambhajinagar",
    "raigarh mh": "raigarh",

    # ---- Tamil Nadu ----
    "kanyakumari": "kanniyakumari",
    "thiruvarur": "tiruvarur",
    "tuticorin": "thoothukkudi",
    "tirupathur": "tirupattur",

    # ---- Telangana ----
    "k v rangareddy": "rangareddy",

    # ---- Assam ----
    "north cachar hills": "dima hasao",

    # ---- Garbage collapses ----
    "andamans": np.nan,
    "nicobars": np.nan,
    "leh ladakh": "leh",
    "bijapur kar": "bijapur",
    "mammit": "mamit",
})


def make_key(s):
    if pd.isna(s):
        return np.nan

    s = s.lower()

    s = re.sub(r"[\s\-]", "", s)
    s = re.sub(r"[aeiou]","",s)
    return s


def clean_district_column(df, col="district"):
    df = df.copy()

    df["_raw"] = df[col]

    # normalize
    df["_norm"] = df[col].apply(normalize_district)

    # garbage removal
    df.loc[df["_norm"].apply(is_garbage), "_norm"] = np.nan

    # canonical mapping
    df["_canon"] = df["_norm"].map(
        lambda x: CANONICAL_MAP.get(x, x) if pd.notna(x) else np.nan
    )

    # build grouping key
    df["_key"] = df["_canon"].apply(make_key)

    # auto-collapse by dominant spelling
    key_to_canon = {}

    valid = df.dropna(subset=["_canon", "_key"])

    for key, grp in valid.groupby("_key"):
        canonical = grp["_canon"].value_counts().idxmax()
        key_to_canon[key] = canonical

    df["district_clean"] = df["_key"].map(key_to_canon)

    # formatting
    df["district_clean"] = (
        df["district_clean"]
        .str.replace("-", " ", regex=False)
        .str.title()
        .str.replace(" And ", " and ", regex=False)
        .str.strip()
    )

    return df

In [102]:
cleaned_df = [clean_district_column(state_cleaned_df)]

for idx,df in enumerate(cleaned_df):
    print(df['district_clean'].nunique())
    print(df['district_clean'].unique())

815
['East Khasi Hills' 'Bengaluru Urban' 'Kanpur Nagar' 'Aligarh' 'Sitamarhi'
 'Bahraich' 'Firozabad' 'Purba Champaran' 'Maharajganj' 'Aurangabad'
 'Ghaziabad' 'Faridabad' 'Madhubani' 'Sikar' 'Bhagalpur' 'Amritsar'
 'Gurugram' 'Gautam Buddha Nagar' 'West Delhi' 'Bhind' 'Gwalior' 'Katni'
 'Cooch Behar' 'Lucknow' 'Dinajpur Uttar' 'Marigaon' 'Kokrajhar' 'Agra'
 'Haridwar' 'Nagaon' 'Parbhani' 'West Khasi Hills' 'North West Delhi'
 'West Jaintia Hills' 'Unnao' 'Saharanpur' 'Dibrugarh' 'Udalguri'
 'Chirang' 'Kamrup' 'Dhubri' 'Jaunpur' 'Thane' 'Dhemaji' 'Banaskantha'
 'Tinsukia' 'Spsr Nellore' 'Barpeta' 'Sonitpur' 'Baksa' 'Ludhiana' 'Patna'
 'Kancheepuram' 'Lakhimpur' 'Bongaigaon' 'Vadodara' 'Nainital' 'Dehradun'
 'Hojai' 'Dahod' 'Morbi' 'Raipur' 'Gorakhpur' 'Bulandshahr' 'Mathura'
 'Pashchim Champaran' 'Bijapur' 'Deoghar' 'Muzaffarpur' 'Bundi' 'Kachchh'
 'Ri Bhoi' 'Darrang' 'Ashok Nagar' 'Darjeeling' 'Dima Hasao' 'Ranchi'
 'Surat' 'Nanded' 'Bengaluru' 'Jorhat' 'Gir Somnath' 'Kamrup Metro'
 'Goalpara' 'Bhavnagar' 'Golaghat' 'Nagpur' 'Jalgaon' 'Hingoli'
 'Ahilyanagar' 'Gandhinagar' 'North 24 Parganas' 'Munger' 'Kohima' 'Jalor'
 'Kheda' 'Nalbari' 'Palghar' 'Jodhpur' 'Central Delhi' 'Gaya'
 'Sabarkantha' 'Dimapur' 'Cachar' 'Kheri' 'Rajkot' 'Satara' 'Betul'
 'West Karbi Anglong' 'South Delhi' 'Raigad' 'Uttar Dinajpur' 'Guna'
 'Kaimur Bhabua' 'Dholpur' 'Churachandpur' 'West Champaran' 'Jhargram'
 'Khargone' 'Chhotaudepur' 'Mumbai Suburban' 'Hailakandi' 'Panchmahals'
 'South Salmara Mankachar' 'Budaun' 'Kanpur Dehat' 'Porbandar'
 'West Garo Hills' 'Kapurthala' 'South Garo Hills' 'Nagaur' 'Mysuru'
 'Mahesana' 'Churu' 'Hyderabad' 'Varanasi' 'Lohardaga' 'North Garo Hills'
 'Chhatarpur' 'Nadia' 'Purnia' 'Gurgaon' 'Charaideo' 'Jaipur' 'Saran'
 'Morena' 'Dhar' 'Devbhumi Dwarka' 'East Champaran' 'Tapi' 'Baghpat'
 'Fatehpur' 'South West Khasi Hills' 'Yadgir' 'Nandurbar' 'Etawah'
 'Jalpaiguri' 'Jabalpur' 'Shimla' 'Sibsagar' 'Barwani' 'Botad' 'Junagadh'
 'Balrampur' 'Bara Banki' 'Shivpuri' 'Beed' 'Shahjahanpur' 'Jamnagar'
 'Chandrapur' 'Durg' 'Rangareddy' 'Sirohi' 'Alipurduar' 'South West Delhi'
 'Gonda' 'East Jaintia Hills' 'Bareilly' 'Solapur' 'Sitapur' 'Dumka'
 'Sultanpur' 'Karbi Anglong' 'Bikaner' 'Phek' 'Raisen' 'Shrawasti'
 'East Delhi' 'Jhabua' 'Unakoti' 'Indore' 'Bhopal' 'Dungarpur' 'Chandauli'
 'Bharatpur' 'Mainpuri' 'Godda' 'Muzaffarnagar' 'Siddharthnagar' 'Datia'
 'West Tripura' 'Medchal Malkajgiri' 'Sagar' 'Sheopur' 'Arvalli'
 'Surendra Nagar' 'Maldah' 'Amreli' 'Alwar' 'Ambedkar Nagar' 'Madurai'
 'Pilibhit' 'Champhai' 'Valsad' 'Pakur' 'Vaishali' 'Vidisha' 'Karimganj'
 'Biswanath' 'Burhanpur' 'Kaushambi' 'Pune' 'Punch' 'Jehanabad' 'Jalna'
 'Etah' 'Meerut' 'Baran' 'Sangrur' 'Karauli' 'Anand' 'Longleng'
 'Chandigarh' 'Jamui' 'South Sikkim' 'Panna' 'East Garo Hills' 'Jhalawar'
 'Shahdara' 'Kalaburagi' 'Thanjavur' 'Tuensang' 'Mahisagar' 'Hoshiarpur'
 'Noklak' 'Sukma' 'Khandwa' 'Ajmer' 'West Sikkim' 'Latur' 'Basti' 'Satna'
 'Gurdaspur' 'Hazaribagh' 'Azamgarh' 'Udaipur' 'Kolkata' 'Rampur'
 'The Dangs' 'East Singhbhum' 'Alirajpur' 'Sas Nagar Mohali'
 'South West Garo Hills' 'Moradabad' 'Kota' 'Dewas' 'Navsari'
 'Chumukedima' 'Ahmedabad' 'Nabarangapur' 'Pali' 'Amroha' 'Saiha'
 'Dakshin Dinajpur' 'Bijnor' 'Pudukkottai' 'Bangalore Rural' 'Kalimpong'
 'Deoria' 'Baramula' 'Gopalganj' 'Prayagraj' 'Lalitpur' 'Mewat' 'Hapur'
 'Jammu' 'Bishnupur' 'Saharsa' 'Arwal' 'Hathras' 'Lawngtlai' 'Nashik'
 'Yavatmal' 'Cuddalore' 'Kollam' 'Patiala' 'Katihar' 'Malappuram'
 'Birbhum' 'Siwan' 'Dhule' 'Baloda Bazar' 'Washim' 'Coimbatore' 'Lunglei'
 'Imphal West' 'Kushinagar' 'Thiruvananthapuram' 'Sangli' 'Lakhisarai'
 '24 Paraganas North' 'Banka' 'Salem'
 'Dadra and Nagar Haveli and Daman and Diu' 'Dang' 'Kaithal' 'Vellore'
 'Shravasti' 'Nalanda' 'Jaisalmer' 'Kallakurichi' 'Farrukhabad'
 'Medinipur West' 'Araria' 'Sonipat' 'Chatra' 'Gaurella Pendra Marwahi'
 'Visakhapatnam' 'Buldhana' 'Amravati' 'Hardoi' 'Ernakulam' 'New Delhi'
 'Bhilwara' 'Ramanathapuram' 'Mon' 'Raichur' 'North Delhi' 'Rohtak'
 'Gumla' 'Barmer' 'Kurukshetra' 'Nuh' 'Thrissur' 'S A S Nagar'
 'North East Delhi' 'Purba Bardhaman' 'Ambala' 'Panipat' 'Darbhanga'
 'Ayodhya' 'Khunti' 'Sivasagar' 'Hisar' 'Sivaganga' 'West Kameng' 'Kullu'
 'Khordha' 'Chengalpattu' 'Nawada' 'Hooghly' '24 Paraganas South'
 'Chennai' 'Mumbai' 'Ramanagar' 'Wokha' 'West Singhbhum' 'Sepahijala'
 'Samastipur' 'Zunheboto' 'East Singhbum' 'Sambhal' 'Chittorgarh' 'Bidar'
 'Tonk' 'Longding' 'Jhansi' 'Howrah' 'Raigarh' 'Giridih' 'Akola'
 'North Goa' 'Vijayapura' 'Begusarai' 'Thiruvallur' 'Bhadradri Kothagudem'
 'Hanumangarh' 'Kannur' 'Tarn Taran' 'Majuli' 'Balaghat' 'Kiphire'
 'Dinajpur Dakshin' 'East Nimar' 'Dharashiv' 'Dhanbad' 'Kasganj' 'Shopian'
 'Sehore' 'Kannauj' 'Narsinghpur' 'Bilaspur' 'Kolasib' 'Sawai Madhopur'
 'North Tripura' 'Prakasam' 'Bhojpur' 'Hoshangabad' 'Doda' 'Mokokchung'
 'Gomati' 'Krishna' 'Kurnool' 'Mahabubnagar' 'Medak' 'N T R' 'Nalgonda'
 'Nandyal' 'Nellore' 'Palnadu' 'Sri Potti Sriramulu Nellore'
 'Sri Sathya Sai' 'Srikakulam' 'Tirupati' 'Vizianagaram' 'Warangal'
 'West Godavari' 'Y S R' 'Changlang' 'East Kameng' 'Tawang' 'West Siang'
 'Bajali' 'Sribhumi' 'Buxar' 'Khagaria' 'Kishanganj' 'Madhepura' 'Rohtas'
 'Sheohar' 'Supaul' 'Bastar' 'Bemetara' 'Gariyaband' 'Jashpur' 'Kawardha'
 'Kondagaon' 'Korba' 'Manendragarhchirmiribharatpur' 'Rajnandgaon' 'Sakti'
 'Sarangarh Bilaigarh' 'Surajpur' 'Surguja' 'South Goa' 'Narmada'
 'Bhiwani' 'Charkhi Dadri' 'Fatehabad' 'Jhajjar' 'Jind' 'Mahendragarh'
 'Rewari' 'Sirsa' 'Yamuna Nagar' 'Hamirpur' 'Kangra' 'Mandi' 'Sirmaur'
 'Solan' 'Una' 'Anantnag' 'Badgam' 'Bandipore' 'Kargil' 'Kathua' 'Kupwara'
 'Leh' 'Pulwama' 'Rajouri' 'Ramban' 'Reasi' 'Samba' 'Srinagar' 'Udhampur'
 'Bokaro' 'Garhwa' 'Jamtara' 'Latehar' 'Palamu' 'Purbi Singhbhum'
 'Ramgarh' 'Sahebganj' 'Seraikela Kharsawan' 'Simdega' 'Bagalkot'
 'Ballari' 'Belagavi' 'Belgaum' 'Bellary' 'Chamrajanagar' 'Chickmagalur'
 'Chikkaballapur' 'Chikkamagaluru' 'Chikmagalur' 'Chitradurga'
 'Dakshina Kannada' 'Davangere' 'Dharwad' 'Gadag' 'Gulbarga' 'Hassan'
 'Haveri' 'Kodagu' 'Kolar' 'Koppal' 'Mandya' 'Shimoga' 'Shivamogga'
 'Tumkur' 'Udupi' 'Uttara Kannada' 'Vijayanagara' 'Alappuzha' 'Idukki'
 'Kasaragod' 'Kottayam' 'Kozhikode' 'Palakkad' 'Pathanamthitta' 'Wayanad'
 'Agar Malwa' 'Anuppur' 'Chhindwara' 'Damoh' 'Dindori' 'Maihar' 'Mandla'
 'Mandsaur' 'Narmadapuram' 'Narsimhapur' 'Neemuch' 'Niwari' 'Rajgarh'
 'Ratlam' 'Rewa' 'Seoni' 'Shahdol' 'Shajapur' 'Sidhi' 'Singrauli'
 'Tikamgarh' 'Ujjain' 'West Nimar' 'Ahmed Nagar' 'Bhandara'
 'Chhatrapati Sambhajinagar' 'Gadchiroli' 'Gondiya' 'Kolhapur'
 'Mumbai City' 'Ratnagiri' 'Sindhudurg' 'Wardha' 'Tamenglong' 'Aizawl'
 'Angul' 'Nicobar' 'South Andaman' 'Adilabad' 'Alluri Sitharama Raju'
 'Anakapalli' 'Ananthapuramu' 'Bapatla' 'Chittoor' 'Cuddapah'
 'Dr B R Ambedkar Konaseema' 'East Godavari' 'Eluru' 'Guntur' 'Kakinada'
 'Karimnagar' 'Khammam' 'Balangir' 'Baleshwar' 'Bargarh' 'Boudh' 'Bhadrak'
 'Cuttack' 'Debagarh' 'Dhenkanal' 'Gajapati' 'Ganjam' 'Jajapur'
 'Jagatsinghapur' 'Kalahandi' 'Kandhamal' 'Kendrapara' 'Kendujhar'
 'Koraput' 'Malkangiri' 'Mayurbhanj' 'Nayagarh' 'Nuapada' 'Puri'
 'Rayagada' 'Sambalpur' 'Subarnapur' 'Sundergarh' 'Pondicherry' 'Karaikal'
 'Puducherry' 'Yanam' 'Barnala' 'Bathinda' 'Faridkot' 'Fatehgarh Sahib'
 'Ferozepur' 'Jalandhar' 'Malerkotla' 'Mansa' 'Muktsar' 'Pathankot'
 'Rupnagar' 'Shaheed Bhagat Singh Nagar' 'Sri Muktsar Sahib' 'Banswara'
 'Dausa' 'Ganganagar' 'Jhunjhunu' 'Pratapgarh' 'Rajsamand' nan
 'North Sikkim' 'Ariyalur' 'Dharmapuri' 'Dindigul' 'Erode' 'Kanniyakumari'
 'Karur' 'Krishnagiri' 'Mayiladuthurai' 'Nagapattinam' 'Namakkal'
 'Perambalur' 'Ranipet' 'Tenkasi' 'The Nilgiris' 'Tiruvarur'
 'Thoothukkudi' 'Tiruchirappalli' 'Tirunelveli' 'Tirupattur' 'Tiruppur'
 'Tiruvallur' 'Tiruvannamalai' 'Villupuram' 'Virudhunagar' 'Hanumakonda'
 'Jagitial' 'Jangoan' 'Jayashankar Bhupalpally' 'Jogulamba Gadwal'
 'Kamareddy' 'Komaram Bheem' 'Mahabubabad' 'Mancherial' 'Mulugu'
 'Nagarkurnool' 'Narayanpet' 'Nirmal' 'Nizamabad' 'Peddapalli'
 'Rajanna Sircilla' 'Sangareddy' 'Siddipet' 'Suryapet' 'Vikarabad'
 'Wanaparthy' 'Warangal Rural' 'Warangal Urban' 'Yadadri' 'Khowai'
 'South Tripura' 'Amethi' 'Auraiya' 'Ballia' 'Bhadohi' 'Chitrakoot'
 'Faizabad' 'Ghazipur' 'Mahoba' 'Mau' 'Mirzapur' 'Rae Bareli'
 'Sant Kabir Nagar' 'Sant Ravidas Nagar' 'Sonbhadra' 'Almora' 'Bageshwar'
 'Chamoli' 'Garhwal' 'Pauri Garhwal' 'Pithoragarh' 'Rudraprayag'
 'Tehri Garhwal' 'Udham Singh Nagar' 'Uttarkashi' 'Bankura' 'Barddhaman'
 'Bardhaman' 'East Midnapore' 'Koch Bihar' 'Murshidabad'
 'Paschim Bardhaman' 'Paschim Medinipur' 'Purba Medinipur' 'Purulia'
 'South 24 Parganas' 'South Dinajpur' 'West Midnapore'
 'Parvathipuram Manyam' 'Kurung Kumey' 'Lohit' 'Lower Dibang Valley'
 'Papum Pare' 'Upper Siang' 'Sheikhpura' 'Balod' 'Dhamtari'
 'Gaurela Pendra Marwahi' 'Janjgir Champa' 'Kabeerdham' 'Kanker'
 'Khairagarh Chhuikhadan Gandai' 'Koriya' 'Mahasamund'
 'Mohla Manpur Ambagarh Chouki' 'Mungeli' 'Narayanpur' 'Palwal' 'Chamba'
 'Ganderbal' 'Koderma' 'Hasan' 'Lakshadweep' 'Mauganj' 'Umaria'
 'Imphal East' 'Thoubal' 'Ukhrul' 'Eastern West Khasi Hills' 'Mamit'
 'Serchhip' 'North and Middle Andaman' 'Annamayya' 'North Dinajpur'
 'Jharsuguda' 'Fazilka' 'Moga' 'Kakching' 'East Sikkim' 'Lower Subansiri'
 'Namsai' 'Sheikpura' 'Dakshin Bastar Dantewada' 'Daman' 'Panchkula'
 'Kishtwar' 'Shupiyan' 'Pashchimi Singhbhum' 'Pandhurna'
 'Jyotiba Phule Nagar' 'Sant Ravidas Nagar Bhadohi' 'Meluri' 'Anjaw'
 'East Siang' 'Tamulpur District' 'Dantewada' 'Kulgam' 'Jiribam' 'Saitual'
 'Kra Daadi' 'Upper Subansiri' 'Bhabua' 'Champawat' 'Kamle' 'Shamator'
 'Nawanshahr' 'Monghyr' 'Uttar Bastar Kanker' 'South East Delhi' 'Siang'
 'Tirap' 'Shi Yomi' 'Khawzawl' 'Lahul and Spiti' 'Lower Siang'
 'Bengaluru South' 'Dibang Valley' 'Deeg' 'Leparada'
 'Mohalla Manpur Ambagarh Chowki' 'Tseminyu' 'Hnahthial' 'Pakke Kessang'
 'Pherzawl' 'Jaintia Hills' 'Burdwan' 'Mangan' 'South 24 Pargana' 'Bagpat'
 'Balotra' 'Didwana Kuchaman' 'Salumbar' 'Beawar']

In [98]:
(cleaned_df)

[              date          state          district  pincode  age_0_5  \
 0       02-03-2025      MEGHALAYA  EAST KHASI HILLS   793121       11
 1       09-03-2025      KARNATAKA   BENGALURU URBAN   560043       14
 2       09-03-2025  UTTAR PRADESH      KANPUR NAGAR   208001       29
 3       09-03-2025  UTTAR PRADESH           ALIGARH   202133       62
 4       09-03-2025      KARNATAKA   BENGALURU URBAN   560016       14
 ...            ...            ...               ...      ...      ...
 982994  31-12-2025    WEST BENGAL    WEST MIDNAPORE   721149        2
 982995  31-12-2025    WEST BENGAL    WEST MIDNAPORE   721150        2
 982996  31-12-2025    WEST BENGAL    WEST MIDNAPORE   721305        0
 982997  31-12-2025    WEST BENGAL    WEST MIDNAPORE   721504        1
 982998  31-12-2025    WEST BENGAL    WEST MIDNAPORE   721517        2

         age_5_17  age_18_greater              _raw             _norm  \
 0             61              37  EAST KHASI HILLS  east khasi hills
 1             33              39   BENGALURU URBAN   bengaluru urban
 2             82              12      KANPUR NAGAR      kanpur nagar
 3             29              15           ALIGARH           aligarh
 4             16              21   BENGALURU URBAN   bengaluru urban
 ...          ...             ...               ...               ...
 982994         0               0    WEST MIDNAPORE    west midnapore
 982995         2               0    WEST MIDNAPORE    west midnapore
 982996         1               0    WEST MIDNAPORE    west midnapore
 982997         0               0    WEST MIDNAPORE    west midnapore
 982998         1               0    WEST MIDNAPORE    west midnapore

                   _canon       _key    district_clean
 0       east khasi hills  stkhshlls  East Khasi Hills
 1        bengaluru urban   bnglrrbn   Bengaluru Urban
 2           kanpur nagar    knprngr      Kanpur Nagar
 3                aligarh       lgrh           Aligarh
 4        bengaluru urban   bnglrrbn   Bengaluru Urban
 ...                  ...        ...               ...
 982994    west midnapore   wstmdnpr    West Midnapore
 982995    west midnapore   wstmdnpr    West Midnapore
 982996    west midnapore   wstmdnpr    West Midnapore
 982997    west midnapore   wstmdnpr    West Midnapore
 982998    west midnapore   wstmdnpr    West Midnapore

 [982999 rows x 12 columns]]

In [104]:
df = pd.concat([df[['date','state','district_clean','pincode', 'age_0_5', 'age_5_17','age_18_greater']] for df in cleaned_df],axis=0).reset_index()
df.shape

(982999, 8)

In [106]:
df

,index,date,state,district_clean,pincode,age_0_5,age_5_17,age_18_greater
0,0,02-03-2025,MEGHALAYA,East Khasi Hills,793121,11,61,37
1,1,09-03-2025,KARNATAKA,Bengaluru Urban,560043,14,33,39
2,2,09-03-2025,UTTAR PRADESH,Kanpur Nagar,208001,29,82,12
3,3,09-03-2025,UTTAR PRADESH,Aligarh,202133,62,29,15
4,4,09-03-2025,KARNATAKA,Bengaluru Urban,560016,14,16,21
...,...,...,...,...,...,...,...,...
982994,982994,31-12-2025,WEST BENGAL,West Midnapore,721149,2,0,0
982995,982995,31-12-2025,WEST BENGAL,West Midnapore,721150,2,2,0
982996,982996,31-12-2025,WEST BENGAL,West Midnapore,721305,0,1,0
982997,982997,31-12-2025,WEST BENGAL,West Midnapore,721504,1,0,0
982998,982998,31-12-2025,WEST BENGAL,West Midnapore,721517,2,1,0

In [111]:
df_copy = df.copy()
df_copy = df_copy.drop(columns=['index'])

In [113]:
df_copy["Total Registrations"] = df_copy["age_0_5"] + df_copy["age_5_17"] + df_copy["age_18_greater"]
df_copy.head()

,date,state,district_clean,pincode,age_0_5,age_5_17,age_18_greater,Total Registrations
0,02-03-2025,MEGHALAYA,East Khasi Hills,793121,11,61,37,109
1,09-03-2025,KARNATAKA,Bengaluru Urban,560043,14,33,39,86
2,09-03-2025,UTTAR PRADESH,Kanpur Nagar,208001,29,82,12,123
3,09-03-2025,UTTAR PRADESH,Aligarh,202133,62,29,15,106
4,09-03-2025,KARNATAKA,Bengaluru Urban,560016,14,16,21,51

There is an ambiguity in the data. We have columns age0_5 and age5_17. Do the members of age 5 overlap? is this inclusive, exclusive? We have no way to understand.

Making the Date columns

In [133]:
df_copy['date'] = pd.to_datetime(df_copy['date'],dayfirst=True)

df_copy['day'] = df_copy['date'].dt.day
df_copy['month'] = df_copy['date'].dt.month
df_copy['year'] = df_copy['date'].dt.year
df_copy['dayname'] = df_copy['date'].dt.day_name()
df_copy['dayofweek'] = df_copy['date'].dt.dayofweek
df_copy['quarter'] = df_copy['date'].dt.quarter

df_copy = df_copy.sort_values(by=['date','state','district_clean','pincode'])
df_copy['pincode'] = df_copy['pincode'].apply(str)
df_copy.head(10)

,date,state,district_clean,pincode,age_0_5,age_5_17,age_18_greater,Total Registrations,day,month,year,dayname,dayofweek,quarter
0,2025-03-02,MEGHALAYA,East Khasi Hills,793121,11,61,37,109,2,3,2025,Sunday,6,1
20,2025-03-09,BIHAR,Bhagalpur,812005,13,40,18,71,9,3,2025,Sunday,6,1
17,2025-03-09,BIHAR,Madhubani,847108,18,120,22,160,9,3,2025,Sunday,6,1
29,2025-03-09,BIHAR,Purba Champaran,845304,18,72,12,102,9,3,2025,Sunday,6,1
9,2025-03-09,BIHAR,Purba Champaran,845418,30,48,10,88,9,3,2025,Sunday,6,1
11,2025-03-09,BIHAR,Sitamarhi,843317,35,94,16,145,9,3,2025,Sunday,6,1
13,2025-03-09,BIHAR,Sitamarhi,843324,49,186,34,269,9,3,2025,Sunday,6,1
6,2025-03-09,BIHAR,Sitamarhi,843330,23,24,42,89,9,3,2025,Sunday,6,1
5,2025-03-09,BIHAR,Sitamarhi,843331,20,49,12,81,9,3,2025,Sunday,6,1
24,2025-03-09,DELHI,West Delhi,110018,29,11,15,55,9,3,2025,Sunday,6,1

In [159]:
df_copy['child_ratio'] = df_copy['age_0_5']/(df_copy['Total Registrations']+1)
df_copy['youth_ratio'] = df_copy['age_5_17']/(df_copy['Total Registrations']+1)
df_copy['year_month'] = df_copy['date'].dt.to_period('M').astype(str)
df_copy['is_weekend'] = df_copy['dayofweek'].isin([5,6]).astype(int)

In [160]:
df_copy.head()

,date,state,district_clean,pincode,age_0_5,age_5_17,age_18_greater,Total Registrations,day,month,year,dayname,dayofweek,quarter,youth_ratio,child_ratio,year_month,is_weekend
0,2025-03-02,MEGHALAYA,East Khasi Hills,793121,11,61,37,109,2,3,2025,Sunday,6,1,0.554545,0.100000,2025-03,1
20,2025-03-09,BIHAR,Bhagalpur,812005,13,40,18,71,9,3,2025,Sunday,6,1,0.555556,0.180556,2025-03,1
17,2025-03-09,BIHAR,Madhubani,847108,18,120,22,160,9,3,2025,Sunday,6,1,0.745342,0.111801,2025-03,1
29,2025-03-09,BIHAR,Purba Champaran,845304,18,72,12,102,9,3,2025,Sunday,6,1,0.699029,0.174757,2025-03,1
9,2025-03-09,BIHAR,Purba Champaran,845418,30,48,10,88,9,3,2025,Sunday,6,1,0.539326,0.337079,2025-03,1

In [156]:
df_copy["date"].min()

Timestamp('2025-03-02 00:00:00')

In [161]:
df_copy.to_csv("Refined enrollment.csv",index=False)